---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-frontend
  template:
    metadata:
      labels:
        app: result-frontend
    spec:
      containers:
      - name: result
        image: dockersamples/examplevotingapp_result:before
        ports:
        - containerPort: 80