---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vote-worker-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote-worker     # Target our background engine
  minReplicas: 1
  maxReplicas: 5          # Scale up to 5 instances to clear the queue simultaneously
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 # Scale up if it sustains >30m CPU usage