apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: localstack-backend
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      # Point ESO to your local LocalStack container
      url: http://host.k3d.internal:4566
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: localstack-credentials
            key: aws-access-key-id
          secretAccessKeySecretRef:
            name: localstack-credentials
            key: aws-secret-access-key