---
apiVersion: v1
kind: Service
metadata:
  name: redis  # CoreDNS will allow other apps to find this at "http://redis:6379"
  namespace: default
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis